import datetime
allData = {('10ALE1', '136变'): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                      'deliverNum': 1706037,
                      'name': 'ATS箱',
                      'sequenceNum': '136变',
                      'serialNum': 23,
                      'unit': '台',
                      'unitPrice': 8274},
 ('10AW1', 134): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 134,
                  'serialNum': 101,
                  'unit': '台',
                  'unitPrice': 4467.93},
 ('10AW2', 135): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 135,
                  'serialNum': 102,
                  'unit': '台',
                  'unitPrice': 4683.59},
 ('11ALE1', '143变'): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                      'deliverNum': 1706037,
                      'name': 'ATS箱',
                      'sequenceNum': '143变',
                      'serialNum': 24,
                      'unit': '台',
                      'unitPrice': 7587},
 ('11ATg', '144变'): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                     'deliverNum': 1706037,
                     'name': 'ATS箱',
                     'sequenceNum': '144变',
                     'serialNum': 25,
                     'unit': '台',
                     'unitPrice': 7817},
 ('11AW1', 141): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 141,
                  'serialNum': 103,
                  'unit': '台',
                  'unitPrice': 4467.93},
 ('11AW2', 142): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 142,
                  'serialNum': 104,
                  'unit': '台',
                  'unitPrice': 4683.59},
 ('12ALE1', '150变'): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                      'deliverNum': 1706037,
                      'name': 'ATS箱',
                      'sequenceNum': '150变',
                      'serialNum': 26,
                      'unit': '台',
                      'unitPrice': 8274},
 ('12AW1', 148): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 148,
                  'serialNum': 105,
                  'unit': '台',
                  'unitPrice': 4899.56},
 ('12AW2', 149): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 149,
                  'serialNum': 106,
                  'unit': '台',
                  'unitPrice': 4683.59},
 ('13ALE1', '157变'): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                      'deliverNum': 1706037,
                      'name': 'ATS箱',
                      'sequenceNum': '157变',
                      'serialNum': 27,
                      'unit': '台',
                      'unitPrice': 8274},
 ('13AW1', 155): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 155,
                  'serialNum': 107,
                  'unit': '台',
                  'unitPrice': 4467.93},
 ('13AW2', 156): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                  'deliverNum': 1705183,
                  'name': '电表箱',
                  'sequenceNum': 156,
                  'serialNum': 85,
                  'unit': '台',
                  'unitPrice': 4683.59},
 ('14ALE1', '163变'): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                      'deliverNum': 1706037,
                      'name': 'ATS箱',
                      'sequenceNum': '163变',
                      'serialNum': 28,
                      'unit': '台',
                      'unitPrice': 8274},
 ('14ATg', '165变'): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                     'deliverNum': 1706037,
                     'name': 'ATS箱',
                     'sequenceNum': '165变',
                     'serialNum': 29,
                     'unit': '台',
                     'unitPrice': 7817},
 ('14AW1', 161): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 161,
                  'serialNum': 108,
                  'unit': '台',
                  'unitPrice': 4467.93},
 ('14AW2', 162): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 162,
                  'serialNum': 109,
                  'unit': '台',
                  'unitPrice': 4683.59},
 ('15ALE1', '171变'): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                      'deliverNum': 1706037,
                      'name': 'ATS箱',
                      'sequenceNum': '171变',
                      'serialNum': 30,
                      'unit': '台',
                      'unitPrice': 8274},
 ('15ATkt1', 172): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 9, 0, 0),
                    'deliverNum': 1705045,
                    'name': 'ATS箱',
                    'sequenceNum': 172,
                    'serialNum': 23,
                    'unit': '台',
                    'unitPrice': 11733.58},
 ('15ATkt2', 173): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 9, 0, 0),
                    'deliverNum': 1705045,
                    'name': 'ATS箱',
                    'sequenceNum': 173,
                    'serialNum': 24,
                    'unit': '台',
                    'unitPrice': 11733.58},
 ('15AW1', 169): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 169,
                  'serialNum': 110,
                  'unit': '台',
                  'unitPrice': 4467.93},
 ('15AW2', 170): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 170,
                  'serialNum': 111,
                  'unit': '台',
                  'unitPrice': 4683.59},
 ('16ALE1', '181变'): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                      'deliverNum': 1706037,
                      'name': 'ATS箱',
                      'sequenceNum': '181变',
                      'serialNum': 31,
                      'unit': '台',
                      'unitPrice': 8274},
 ('16AW1', 179): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 179,
                  'serialNum': 112,
                  'unit': '台',
                  'unitPrice': 4467.93},
 ('16AW2', 180): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                  'deliverNum': 1705183,
                  'name': '电表箱',
                  'sequenceNum': 180,
                  'serialNum': 89,
                  'unit': '台',
                  'unitPrice': 4683.59},
 ('17ALE1', '188变'): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                      'deliverNum': 1706037,
                      'name': 'ATS箱',
                      'sequenceNum': '188变',
                      'serialNum': 32,
                      'unit': '台',
                      'unitPrice': 8274},
 ('17ATg', '189变'): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                     'deliverNum': 1706037,
                     'name': 'ATS箱',
                     'sequenceNum': '189变',
                     'serialNum': 33,
                     'unit': '台',
                     'unitPrice': 7817},
 ('17AW1', 186): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 186,
                  'serialNum': 113,
                  'unit': '台',
                  'unitPrice': 4467.93},
 ('17AW2', 187): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 187,
                  'serialNum': 114,
                  'unit': '台',
                  'unitPrice': 4683.59},
 ('18ALE1', '195变'): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                      'deliverNum': 1706037,
                      'name': 'ATS箱',
                      'sequenceNum': '195变',
                      'serialNum': 34,
                      'unit': '台',
                      'unitPrice': 8274},
 ('18AW1', 193): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 193,
                  'serialNum': 115,
                  'unit': '台',
                  'unitPrice': 4467.93},
 ('18AW2', 194): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                  'deliverNum': '1705183',
                  'name': '电表箱',
                  'sequenceNum': 194,
                  'serialNum': 91,
                  'unit': '台',
                  'unitPrice': 4683.59},
 ('19ALE1', '202变'): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                      'deliverNum': 1706037,
                      'name': 'ATS箱',
                      'sequenceNum': '202变',
                      'serialNum': 35,
                      'unit': '台',
                      'unitPrice': 8274},
 ('19AW1', 200): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 200,
                  'serialNum': 116,
                  'unit': '台',
                  'unitPrice': 4467.93},
 ('19AW2', 201): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                  'deliverNum': 1706038,
                  'name': '电表箱',
                  'sequenceNum': 201,
                  'serialNum': 165,
                  'unit': '台',
                  'unitPrice': 4683.59},
 ('1AL1', 78): {'amount': 1,
                'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                'deliverNum': 1706115,
                'name': '配电箱',
                'sequenceNum': 78,
                'serialNum': 201,
                'unit': '台',
                'unitPrice': 4191},
 ('1ALE1', '79变'): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                    'deliverNum': 1706037,
                    'name': 'ATS箱',
                    'sequenceNum': '79变',
                    'serialNum': 11,
                    'unit': '台',
                    'unitPrice': 7525},
 ('1ATxf', 77): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                 'deliverNum': 1706116,
                 'name': '配电箱',
                 'sequenceNum': 77,
                 'serialNum': 202,
                 'unit': '台',
                 'unitPrice': 8393},
 ('1AW2', 228): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                 'deliverNum': 1706038,
                 'name': '电表箱',
                 'sequenceNum': 228,
                 'serialNum': 166,
                 'unit': '台',
                 'unitPrice': 3185.93},
 ('20ALE1', '208变'): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                      'deliverNum': 1706037,
                      'name': 'ATS箱',
                      'sequenceNum': '208变',
                      'serialNum': 36,
                      'unit': '台',
                      'unitPrice': 7629},
 ('20ATg', '210变'): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                     'deliverNum': 1706037,
                     'name': 'ATS箱',
                     'sequenceNum': '210变',
                     'serialNum': 37,
                     'unit': '台',
                     'unitPrice': 7817},
 ('20AW1', 206): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 206,
                  'serialNum': 117,
                  'unit': '台',
                  'unitPrice': 4899.56},
 ('20AW2', 207): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                  'deliverNum': '1706007',
                  'name': '电表箱',
                  'sequenceNum': 207,
                  'serialNum': 118,
                  'unit': '台',
                  'unitPrice': 4683.59},
 ('2ACf1', 84): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                 'deliverNum': 1706118,
                 'name': '控制箱',
                 'sequenceNum': 84,
                 'serialNum': 197,
                 'unit': '台',
                 'unitPrice': 1210.19},
 ('2ACxf1 ', '增2-1'): {'amount': 1,
                       'deliverDate': datetime.datetime(2017, 9, 14, 0, 0),
                       'deliverNum': 1709095,
                       'name': '配电箱',
                       'sequenceNum': '增2-1',
                       'serialNum': 22,
                       'unit': '台',
                       'unitPrice': 6343.09},
 ('2AL1', 83): {'amount': 1,
                'deliverDate': datetime.datetime(2017, 9, 14, 0, 0),
                'deliverNum': 1709094,
                'name': '配电箱底芯',
                'sequenceNum': 83,
                'serialNum': 19,
                'unit': '台',
                'unitPrice': 1418},
 ('2ALE1', '82变'): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                    'deliverNum': 1706037,
                    'name': 'ATS箱',
                    'sequenceNum': '82变',
                    'serialNum': 13,
                    'unit': '台',
                    'unitPrice': 7484},
 ('2ATg', '81变'): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                   'deliverNum': 1706037,
                   'name': 'ATS箱',
                   'sequenceNum': '81变',
                   'serialNum': 12,
                   'unit': '台',
                   'unitPrice': 7794},
 ('2AW1', 80): {'amount': 1,
                'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                'deliverNum': 1706038,
                'name': '电表箱',
                'sequenceNum': 80,
                'serialNum': 157,
                'unit': '台',
                'unitPrice': 3108.93},
 ('2AW2', 229): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                 'deliverNum': 1706038,
                 'name': '电表箱',
                 'sequenceNum': 229,
                 'serialNum': 167,
                 'unit': '台',
                 'unitPrice': 3185.93},
 ('3*35+2*16', 17): {'amount': 2,
                     'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                     'deliverNum': 1706034,
                     'name': 'T接箱',
                     'sequenceNum': 17,
                     'serialNum': 120,
                     'unit': '台',
                     'unitPrice': 501.94},
 ('3ACf1', 90): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                 'deliverNum': 1706118,
                 'name': '控制箱',
                 'sequenceNum': 90,
                 'serialNum': 198,
                 'unit': '台',
                 'unitPrice': 2687.11},
 ('3ACxf1', 89): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                  'deliverNum': 1706114,
                  'name': 'ATS箱',
                  'sequenceNum': 89,
                  'serialNum': 186,
                  'unit': '台',
                  'unitPrice': 6343.09},
 ('3ALE1', '87变'): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                    'deliverNum': 1706037,
                    'name': 'ATS箱',
                    'sequenceNum': '87变',
                    'serialNum': 14,
                    'unit': '台',
                    'unitPrice': 7613},
 ('3AW1', 85): {'amount': 1,
                'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                'deliverNum': 1706038,
                'name': '电表箱',
                'sequenceNum': 85,
                'serialNum': 158,
                'unit': '台',
                'unitPrice': 4317.18},
 ('3AW2', 86): {'amount': 1,
                'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                'deliverNum': 1706038,
                'name': '配电箱',
                'sequenceNum': 86,
                'serialNum': 159,
                'unit': '台',
                'unitPrice': 4683.59},
 ('4ACf1', 96): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                 'deliverNum': 1706118,
                 'name': '控制箱',
                 'sequenceNum': 96,
                 'serialNum': 200,
                 'unit': '台',
                 'unitPrice': 1210.16},
 ('4ALE1', '93变'): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                    'deliverNum': 1706037,
                    'name': 'ATS箱',
                    'sequenceNum': '93变',
                    'serialNum': 15,
                    'unit': '台',
                    'unitPrice': 7654},
 ('4ALcf', 95): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                 'deliverNum': 1706118,
                 'name': '配电箱',
                 'sequenceNum': 95,
                 'serialNum': 199,
                 'unit': '台',
                 'unitPrice': 1694.48},
 ('4AW1', 91): {'amount': 1,
                'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                'deliverNum': 1706038,
                'name': '电表箱',
                'sequenceNum': 91,
                'serialNum': 160,
                'unit': '台',
                'unitPrice': 3587.87},
 ('4AW2', 92): {'amount': 1,
                'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                'deliverNum': 1706038,
                'name': '电表箱',
                'sequenceNum': 92,
                'serialNum': 161,
                'unit': '台',
                'unitPrice': 5347.34},
 ('5ALE1', '102变'): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                     'deliverNum': 1706037,
                     'name': 'ATS箱',
                     'sequenceNum': '102变',
                     'serialNum': 16,
                     'unit': '台',
                     'unitPrice': 7613},
 ('5ATg', '103变'): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                    'deliverNum': 1706037,
                    'name': 'ATS箱',
                    'sequenceNum': '103变',
                    'serialNum': 17,
                    'unit': '台',
                    'unitPrice': 7817},
 ('5AW1', 100): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                 'deliverNum': 1706038,
                 'name': '电表箱',
                 'sequenceNum': 100,
                 'serialNum': 162,
                 'unit': '台',
                 'unitPrice': 3508.13},
 ('5AW2', 101): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                 'deliverNum': 1706038,
                 'name': '配电箱',
                 'sequenceNum': 101,
                 'serialNum': 163,
                 'unit': '台',
                 'unitPrice': 4683.59},
 ('5~20层主机配电箱', 233): {'amount': 8,
                       'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                       'deliverNum': 1706038,
                       'name': '配电箱',
                       'sequenceNum': 233,
                       'serialNum': 171,
                       'unit': '台',
                       'unitPrice': 13408.16},
 ('6ALE1', '106变'): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                     'deliverNum': 1706037,
                     'name': 'ATS箱',
                     'sequenceNum': '106变',
                     'serialNum': 18,
                     'unit': '台',
                     'unitPrice': 8274},
 ('6AW1', 104): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                 'deliverNum': '1706007',
                 'name': '电表箱',
                 'sequenceNum': 104,
                 'serialNum': 96,
                 'unit': '台',
                 'unitPrice': 4581.78},
 ('6AW2', 105): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                 'deliverNum': 1705183,
                 'name': '电表箱',
                 'sequenceNum': 105,
                 'serialNum': 76,
                 'unit': '台',
                 'unitPrice': 4188.13},
 ('7ALE1', '115变'): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                     'deliverNum': 1706037,
                     'name': 'ATS箱',
                     'sequenceNum': '115变',
                     'serialNum': 19,
                     'unit': '台',
                     'unitPrice': 8274},
 ('7AW1', 113): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                 'deliverNum': '1706007',
                 'name': '电表箱',
                 'sequenceNum': 113,
                 'serialNum': 97,
                 'unit': '台',
                 'unitPrice': 4467.93},
 ('7AW2', 114): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                 'deliverNum': 1706038,
                 'name': '电表箱',
                 'sequenceNum': 114,
                 'serialNum': 164,
                 'unit': '台',
                 'unitPrice': 5654.23},
 ('8ALE1', '121变'): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                     'deliverNum': 1706037,
                     'name': 'ATS箱',
                     'sequenceNum': '121变',
                     'serialNum': 20,
                     'unit': '台',
                     'unitPrice': 8274},
 ('8ATg', '123变'): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                    'deliverNum': 1706037,
                    'name': 'ATS箱',
                    'sequenceNum': '123变',
                    'serialNum': 21,
                    'unit': '台',
                    'unitPrice': 7817},
 ('8AW1', 119): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                 'deliverNum': '1706007',
                 'name': '电表箱',
                 'sequenceNum': 119,
                 'serialNum': 98,
                 'unit': '台',
                 'unitPrice': 4467.93},
 ('8AW2', 120): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                 'deliverNum': 1705183,
                 'name': '电表箱',
                 'sequenceNum': 120,
                 'serialNum': 79,
                 'unit': '台',
                 'unitPrice': 4683.59},
 ('9ALE1', '130变'): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                     'deliverNum': 1706037,
                     'name': 'ATS箱',
                     'sequenceNum': '130变',
                     'serialNum': 22,
                     'unit': '台',
                     'unitPrice': 8274},
 ('9AW1', 128): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                 'deliverNum': '1706007',
                 'name': '电表箱',
                 'sequenceNum': 128,
                 'serialNum': 99,
                 'unit': '台',
                 'unitPrice': 4467.93},
 ('9AW2', 129): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                 'deliverNum': '1706007',
                 'name': '电表箱',
                 'sequenceNum': 129,
                 'serialNum': 100,
                 'unit': '台',
                 'unitPrice': 4683.59},
 ('AL5', 98): {'amount': 1,
               'deliverDate': datetime.datetime(2017, 9, 14, 0, 0),
               'deliverNum': 1709094,
               'name': '配电箱底芯',
               'sequenceNum': 98,
               'serialNum': 21,
               'unit': '台',
               'unitPrice': 390},
 ('B-ACf1', 108): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                   'deliverNum': 1706038,
                   'name': '控制箱',
                   'sequenceNum': 108,
                   'serialNum': 172,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf1', 116): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                   'deliverNum': 1706038,
                   'name': '控制箱',
                   'sequenceNum': 116,
                   'serialNum': 173,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf1', 124): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                   'deliverNum': 1706038,
                   'name': '控制箱',
                   'sequenceNum': 124,
                   'serialNum': 174,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf1', 131): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                   'deliverNum': 1706038,
                   'name': '控制箱',
                   'sequenceNum': 131,
                   'serialNum': 175,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf1', 138): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                   'deliverNum': 1706038,
                   'name': '控制箱',
                   'sequenceNum': 138,
                   'serialNum': 176,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf1', 145): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                   'deliverNum': 1706038,
                   'name': '控制箱',
                   'sequenceNum': 145,
                   'serialNum': 177,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf1', 152): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                   'deliverNum': 1706038,
                   'name': '控制箱',
                   'sequenceNum': 152,
                   'serialNum': 178,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf1', 158): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                   'deliverNum': 1706038,
                   'name': '控制箱',
                   'sequenceNum': 158,
                   'serialNum': 179,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf1', 166): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                   'deliverNum': 1708071,
                   'name': '控制箱',
                   'sequenceNum': 166,
                   'serialNum': 1,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf1', 176): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                   'deliverNum': 1706038,
                   'name': '控制箱',
                   'sequenceNum': 176,
                   'serialNum': 180,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf1', 183): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                   'deliverNum': 1706038,
                   'name': '控制箱',
                   'sequenceNum': 183,
                   'serialNum': 181,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf1', 190): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                   'deliverNum': 1706038,
                   'name': '控制箱',
                   'sequenceNum': 190,
                   'serialNum': 182,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf1', 197): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                   'deliverNum': 1706038,
                   'name': '控制箱',
                   'sequenceNum': 197,
                   'serialNum': 183,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf1', 203): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                   'deliverNum': 1706038,
                   'name': '控制箱',
                   'sequenceNum': 203,
                   'serialNum': 184,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf1', 211): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                   'deliverNum': 1706038,
                   'name': '控制箱',
                   'sequenceNum': 211,
                   'serialNum': 185,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf2', 99): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                  'deliverNum': 1705183,
                  'name': '控制箱',
                  'sequenceNum': 99,
                  'serialNum': 75,
                  'unit': '台',
                  'unitPrice': 1210.16},
 ('B-ACf2', 109): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                   'deliverNum': 1705183,
                   'name': '控制箱',
                   'sequenceNum': 109,
                   'serialNum': 77,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf2', 117): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                   'deliverNum': 1705183,
                   'name': '控制箱',
                   'sequenceNum': 117,
                   'serialNum': 78,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf2', 125): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                   'deliverNum': 1705183,
                   'name': '控制箱',
                   'sequenceNum': 125,
                   'serialNum': 80,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf2', 132): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                   'deliverNum': 1705183,
                   'name': '控制箱',
                   'sequenceNum': 132,
                   'serialNum': 81,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf2', 139): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                   'deliverNum': 1705183,
                   'name': '控制箱',
                   'sequenceNum': 139,
                   'serialNum': 82,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf2', 146): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                   'deliverNum': 1705183,
                   'name': '控制箱',
                   'sequenceNum': 146,
                   'serialNum': 83,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf2', 153): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                   'deliverNum': 1705183,
                   'name': '控制箱',
                   'sequenceNum': 153,
                   'serialNum': 84,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf2', 159): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                   'deliverNum': 1705183,
                   'name': '控制箱',
                   'sequenceNum': 159,
                   'serialNum': 86,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf2', 167): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                   'deliverNum': 1705183,
                   'name': '控制箱',
                   'sequenceNum': 167,
                   'serialNum': 87,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf2', 177): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                   'deliverNum': 1705183,
                   'name': '控制箱',
                   'sequenceNum': 177,
                   'serialNum': 88,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf2', 184): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                   'deliverNum': 1705183,
                   'name': '控制箱',
                   'sequenceNum': 184,
                   'serialNum': 90,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf2', 191): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                   'deliverNum': 1705183,
                   'name': '控制箱',
                   'sequenceNum': 191,
                   'serialNum': 94,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf2', 198): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                   'deliverNum': 1705183,
                   'name': '控制箱',
                   'sequenceNum': 198,
                   'serialNum': 92,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf2', 204): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                   'deliverNum': 1705183,
                   'name': '控制箱',
                   'sequenceNum': 204,
                   'serialNum': 95,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-ACf2', 212): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 25, 0, 0),
                   'deliverNum': 1705183,
                   'name': '控制箱',
                   'sequenceNum': 212,
                   'serialNum': 93,
                   'unit': '台',
                   'unitPrice': 1210.16},
 ('B-AL1', 110): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 110,
                  'serialNum': 2,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL2', 97): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 9, 14, 0, 0),
                 'deliverNum': 1709094,
                 'name': '配电箱底芯',
                 'sequenceNum': 97,
                 'serialNum': 20,
                 'unit': '台',
                 'unitPrice': 390},
 ('B-AL2', 111): {'amount': 5,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 111,
                  'serialNum': 3,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL3', 112): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 112,
                  'serialNum': 4,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL3', 118): {'amount': 5,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 118,
                  'serialNum': 5,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL3', 127): {'amount': 5,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 127,
                  'serialNum': 6,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL3', 133): {'amount': 5,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 133,
                  'serialNum': 7,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL3', 140): {'amount': 5,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 140,
                  'serialNum': 8,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL3', 147): {'amount': 5,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 147,
                  'serialNum': 9,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL3', 154): {'amount': 5,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 154,
                  'serialNum': 10,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL3', 160): {'amount': 5,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 160,
                  'serialNum': 11,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL3', 168): {'amount': 5,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 168,
                  'serialNum': 12,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL3', 178): {'amount': 5,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 178,
                  'serialNum': 13,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL3', 185): {'amount': 5,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 185,
                  'serialNum': 14,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL3', 192): {'amount': 5,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 192,
                  'serialNum': 15,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL3', 199): {'amount': 5,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 199,
                  'serialNum': 16,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL3', 205): {'amount': 5,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 205,
                  'serialNum': 17,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('B-AL3', 213): {'amount': 5,
                  'deliverDate': datetime.datetime(2017, 8, 11, 0, 0),
                  'deliverNum': 1708071,
                  'name': '配电箱',
                  'sequenceNum': 213,
                  'serialNum': 18,
                  'unit': '台',
                  'unitPrice': 368.9},
 ('D1ACf2-1', 39): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                    'deliverNum': 1705067,
                    'name': '控制箱',
                    'sequenceNum': 39,
                    'serialNum': 34,
                    'unit': '台',
                    'unitPrice': 1210.16},
 ('D1ACf2-2', 40): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                    'deliverNum': 1705067,
                    'name': '控制箱',
                    'sequenceNum': 40,
                    'serialNum': 35,
                    'unit': '台',
                    'unitPrice': 2865.01},
 ('D1ACf2-3', 41): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                    'deliverNum': 1705067,
                    'name': '控制箱',
                    'sequenceNum': 41,
                    'serialNum': 36,
                    'unit': '台',
                    'unitPrice': 1210.16},
 ('D1ACf2-4', 42): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                    'deliverNum': 1705067,
                    'name': '控制箱',
                    'sequenceNum': 42,
                    'serialNum': 37,
                    'unit': '台',
                    'unitPrice': 1210.16},
 ('D1ACs1-1', 33): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                    'deliverNum': 1705067,
                    'name': 'ATS箱',
                    'sequenceNum': 33,
                    'serialNum': 32,
                    'unit': '台',
                    'unitPrice': 7513.31},
 ('D1ACs1-2', 34): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                    'deliverNum': 1705067,
                    'name': 'ATS箱',
                    'sequenceNum': 34,
                    'serialNum': 33,
                    'unit': '台',
                    'unitPrice': 7513.31},
 ('D1ACxf1-1', 35): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 8, 4, 0, 0),
                     'deliverNum': 1708024,
                     'name': 'ATS箱',
                     'sequenceNum': 35,
                     'serialNum': 206,
                     'unit': '台',
                     'unitPrice': 6343.29},
 ('D1ACxf1-2', 36): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 8, 4, 0, 0),
                     'deliverNum': 1708024,
                     'name': 'ATS箱',
                     'sequenceNum': 36,
                     'serialNum': 207,
                     'unit': '台',
                     'unitPrice': 6343.29},
 ('D1ACxf2-1', 37): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 8, 4, 0, 0),
                     'deliverNum': 1708024,
                     'name': 'ATS箱',
                     'sequenceNum': 37,
                     'serialNum': 208,
                     'unit': '台',
                     'unitPrice': 6343.29},
 ('D1ACxf2-2', 38): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 8, 4, 0, 0),
                     'deliverNum': 1708024,
                     'name': 'ATS箱',
                     'sequenceNum': 38,
                     'serialNum': 209,
                     'unit': '台',
                     'unitPrice': 6330.35},
 ('D1AL1', '29变'): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                    'deliverNum': 1706037,
                    'name': '配电箱',
                    'sequenceNum': '29变',
                    'serialNum': 4,
                    'unit': '台',
                    'unitPrice': 3304},
 ('D1ALE1', '27变'): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                     'deliverNum': 1706037,
                     'name': 'ATS箱',
                     'sequenceNum': '27变',
                     'serialNum': 2,
                     'unit': '台',
                     'unitPrice': 7592},
 ('D1ALE2', '28变'): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                     'deliverNum': 1706037,
                     'name': 'ATS箱',
                     'sequenceNum': '28变',
                     'serialNum': 3,
                     'unit': '台',
                     'unitPrice': 7484},
 ('D1AP2', 26): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                 'deliverNum': 1705067,
                 'name': '配电箱',
                 'sequenceNum': 26,
                 'serialNum': 31,
                 'unit': '台',
                 'unitPrice': 5760.67},
 ('D1APE1-1', 19): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                    'deliverNum': 1705067,
                    'name': '配电箱',
                    'sequenceNum': 19,
                    'serialNum': 26,
                    'unit': '台',
                    'unitPrice': 4352.6},
 ('D1APE1-2', 20): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                    'deliverNum': 1705067,
                    'name': '配电箱',
                    'sequenceNum': 20,
                    'serialNum': 27,
                    'unit': '台',
                    'unitPrice': 4352.6},
 ('D1APE2-1', 21): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                    'deliverNum': 1705067,
                    'name': '配电箱',
                    'sequenceNum': 21,
                    'serialNum': 28,
                    'unit': '台',
                    'unitPrice': 3571.27},
 ('D1APE2-2', 22): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                    'deliverNum': 1705067,
                    'name': '配电箱',
                    'sequenceNum': 22,
                    'serialNum': 29,
                    'unit': '台',
                    'unitPrice': 3571.27},
 ('D1APys', 30): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                  'deliverNum': 1706118,
                  'name': '配电箱',
                  'sequenceNum': 30,
                  'serialNum': 196,
                  'unit': '台',
                  'unitPrice': 3176.91},
 ('D1ATdt', 31): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                  'deliverNum': 1705067,
                  'name': 'ATS箱',
                  'sequenceNum': 31,
                  'serialNum': 38,
                  'unit': '台',
                  'unitPrice': 7234.08},
 ('D1ZAL1', 25): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                  'deliverNum': 1705067,
                  'name': '配电箱',
                  'sequenceNum': 25,
                  'serialNum': 30,
                  'unit': '台',
                  'unitPrice': 7706.04},
 ('D1ZALE1', 23): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                   'deliverNum': 1706118,
                   'name': '配电箱',
                   'sequenceNum': 23,
                   'serialNum': 194,
                   'unit': '台',
                   'unitPrice': 4625.93},
 ('D1ZALE2', 24): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                   'deliverNum': 1706118,
                   'name': '配电箱',
                   'sequenceNum': 24,
                   'serialNum': 195,
                   'unit': '台',
                   'unitPrice': 4625.93},
 ('D2ACf2-1', 56): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 18, 0, 0),
                    'deliverNum': 1705134,
                    'name': '控制箱',
                    'sequenceNum': 56,
                    'serialNum': 64,
                    'unit': '台',
                    'unitPrice': 1210.16},
 ('D2ACf2-2', 57): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 18, 0, 0),
                    'deliverNum': 1705134,
                    'name': '控制箱',
                    'sequenceNum': 57,
                    'serialNum': 65,
                    'unit': '台',
                    'unitPrice': 2903.81},
 ('D2ACxf1-1', 49): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 8, 4, 0, 0),
                     'deliverNum': 1708024,
                     'name': 'ATS箱',
                     'sequenceNum': 49,
                     'serialNum': 210,
                     'unit': '台',
                     'unitPrice': 6343.29},
 ('D2ACxf1-2', 50): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 8, 4, 0, 0),
                     'deliverNum': 1708024,
                     'name': 'ATS箱',
                     'sequenceNum': 50,
                     'serialNum': 211,
                     'unit': '台',
                     'unitPrice': 6343.29},
 ('D2ACxf1-3', 51): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 8, 4, 0, 0),
                     'deliverNum': 1708024,
                     'name': 'ATS箱',
                     'sequenceNum': 51,
                     'serialNum': 212,
                     'unit': '台',
                     'unitPrice': 6343.29},
 ('D2ACxf1-4', 52): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 8, 4, 0, 0),
                     'deliverNum': 1708024,
                     'name': 'ATS箱',
                     'sequenceNum': 52,
                     'serialNum': 213,
                     'unit': '台',
                     'unitPrice': 6330.35},
 ('D2ACxs2-1', 53): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 5, 18, 0, 0),
                     'deliverNum': 1705134,
                     'name': '配电箱',
                     'sequenceNum': 53,
                     'serialNum': 62,
                     'unit': '台',
                     'unitPrice': 3118.51},
 ('D2ACxs2-2', 54): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 5, 18, 0, 0),
                     'deliverNum': 1705134,
                     'name': '配电箱',
                     'sequenceNum': 54,
                     'serialNum': 63,
                     'unit': '台',
                     'unitPrice': 3118.51},
 ('D2AL1', '45变'): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                    'deliverNum': 1706037,
                    'name': '配电箱',
                    'sequenceNum': '45变',
                    'serialNum': 5,
                    'unit': '台',
                    'unitPrice': 3304},
 ('D2AL2', '46变'): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                    'deliverNum': 1706037,
                    'name': '配电箱',
                    'sequenceNum': '46变',
                    'serialNum': 6,
                    'unit': '台',
                    'unitPrice': 3304},
 ('D2ALE1', '47变'): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                     'deliverNum': 1706037,
                     'name': 'ATS箱',
                     'sequenceNum': '47变',
                     'serialNum': 7,
                     'unit': '台',
                     'unitPrice': 7592},
 ('D2ALE2', '48变'): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                     'deliverNum': 1706037,
                     'name': 'ATS箱',
                     'sequenceNum': '48变',
                     'serialNum': 8,
                     'unit': '台',
                     'unitPrice': 7484},
 ('D2APE1-1', 43): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                    'deliverNum': 1705067,
                    'name': '配电箱',
                    'sequenceNum': 43,
                    'serialNum': 39,
                    'unit': '台',
                    'unitPrice': 4563.68},
 ('D2APE1-2', 44): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                    'deliverNum': 1705067,
                    'name': '配电箱',
                    'sequenceNum': 44,
                    'serialNum': 40,
                    'unit': '台',
                    'unitPrice': 4563.68},
 ('D2APsh', 55): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                  'deliverNum': 1706118,
                  'name': '动力柜',
                  'sequenceNum': 55,
                  'serialNum': 190,
                  'unit': '台',
                  'unitPrice': 15740.21},
 ('D2AT2-xfb1', 58): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                      'deliverNum': 1706118,
                      'name': '馈电柜',
                      'sequenceNum': 58,
                      'serialNum': 191,
                      'unit': '台',
                      'unitPrice': 39206},
 ('D2AT2-xfb2', 59): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                      'deliverNum': 1706120,
                      'name': '馈电柜',
                      'sequenceNum': 59,
                      'serialNum': 203,
                      'unit': '台',
                      'unitPrice': 25153},
 ('D2AT2-xfb3', 60): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                      'deliverNum': 1706120,
                      'name': '馈电柜',
                      'sequenceNum': 60,
                      'serialNum': 204,
                      'unit': '台',
                      'unitPrice': 24417},
 ('D2AT2-xfb4', 61): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                      'deliverNum': 1706118,
                      'name': '馈电柜',
                      'sequenceNum': 61,
                      'serialNum': 192,
                      'unit': '台',
                      'unitPrice': 9045.75},
 ('D3ACs1-1', 70): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 18, 0, 0),
                    'deliverNum': 1705134,
                    'name': 'ATS箱',
                    'sequenceNum': 70,
                    'serialNum': 68,
                    'unit': '台',
                    'unitPrice': 7383.97},
 ('D3ACs1-2', 71): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 18, 0, 0),
                    'deliverNum': 1705134,
                    'name': 'ATS箱',
                    'sequenceNum': 71,
                    'serialNum': 69,
                    'unit': '台',
                    'unitPrice': 7383.97},
 ('D3ACs1-3', 72): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 18, 0, 0),
                    'deliverNum': 1705134,
                    'name': 'ATS箱',
                    'sequenceNum': 72,
                    'serialNum': 70,
                    'unit': '台',
                    'unitPrice': 7383.97},
 ('D3ACs1-4', 73): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 18, 0, 0),
                    'deliverNum': 1705134,
                    'name': 'ATS箱',
                    'sequenceNum': 73,
                    'serialNum': 71,
                    'unit': '台',
                    'unitPrice': 7383.97},
 ('D3ACs1-5', 74): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 18, 0, 0),
                    'deliverNum': 1705134,
                    'name': 'ATS箱',
                    'sequenceNum': 74,
                    'serialNum': 72,
                    'unit': '台',
                    'unitPrice': 7383.97},
 ('D3ACs1-6', 75): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 18, 0, 0),
                    'deliverNum': 1705134,
                    'name': 'ATS箱',
                    'sequenceNum': 75,
                    'serialNum': 73,
                    'unit': '台',
                    'unitPrice': 7383.97},
 ('D3ACxf1-1', 67): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 8, 4, 0, 0),
                     'deliverNum': 1708024,
                     'name': 'ATS箱',
                     'sequenceNum': 67,
                     'serialNum': 214,
                     'unit': '台',
                     'unitPrice': 6343.36},
 ('D3ACxf1-2', 68): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 8, 4, 0, 0),
                     'deliverNum': 1708024,
                     'name': 'ATS箱',
                     'sequenceNum': 68,
                     'serialNum': 215,
                     'unit': '台',
                     'unitPrice': 6343.36},
 ('D3ACxf1-3', 69): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 8, 4, 0, 0),
                     'deliverNum': 1708024,
                     'name': 'ATS箱',
                     'sequenceNum': 69,
                     'serialNum': 216,
                     'unit': '台',
                     'unitPrice': 7221},
 ('D3ACxs1-1', 76): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 5, 18, 0, 0),
                     'deliverNum': 1705134,
                     'name': 'ATS箱',
                     'sequenceNum': 76,
                     'serialNum': 74,
                     'unit': '台',
                     'unitPrice': 7383.97},
 ('D3AL1', '65变'): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                    'deliverNum': 1706037,
                    'name': '配电箱',
                    'sequenceNum': '65变',
                    'serialNum': 9,
                    'unit': '台',
                    'unitPrice': 3304},
 ('D3ALE1', '66变'): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                     'deliverNum': 1706037,
                     'name': 'ATS箱',
                     'sequenceNum': '66变',
                     'serialNum': 10,
                     'unit': '台',
                     'unitPrice': 7592},
 ('D3APE1-1', 63): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 18, 0, 0),
                    'deliverNum': 1705134,
                    'name': '配电箱',
                    'sequenceNum': 63,
                    'serialNum': 66,
                    'unit': '台',
                    'unitPrice': 4271.27},
 ('D3APE1-2', 64): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 18, 0, 0),
                    'deliverNum': 1705134,
                    'name': '配电箱',
                    'sequenceNum': 64,
                    'serialNum': 67,
                    'unit': '台',
                    'unitPrice': 7368.91},
 ('WD-ATRF', 227): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                    'deliverNum': 1705067,
                    'name': 'ATS箱',
                    'sequenceNum': 227,
                    'serialNum': 47,
                    'unit': '台',
                    'unitPrice': 10669.91},
 ('WDACf1', 226): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                   'deliverNum': 1705067,
                   'name': '配电箱',
                   'sequenceNum': 226,
                   'serialNum': 46,
                   'unit': '台',
                   'unitPrice': 7316.63},
 ('WDACwy', 225): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                   'deliverNum': 1705067,
                   'name': 'ATS箱',
                   'sequenceNum': 225,
                   'serialNum': 45,
                   'unit': '台',
                   'unitPrice': 9448.16},
 ('WDACxf1', 222): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 8, 4, 0, 0),
                    'deliverNum': 1708024,
                    'name': 'ATS箱',
                    'sequenceNum': 222,
                    'serialNum': 217,
                    'unit': '台',
                    'unitPrice': 8717.89},
 ('WDACxf2', 223): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 8, 4, 0, 0),
                    'deliverNum': 1708024,
                    'name': 'ATS箱',
                    'sequenceNum': 223,
                    'serialNum': 218,
                    'unit': '台',
                    'unitPrice': 10602.66},
 ('WDACxf3', 224): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 8, 4, 0, 0),
                    'deliverNum': 1708024,
                    'name': 'ATS箱',
                    'sequenceNum': 224,
                    'serialNum': 219,
                    'unit': '台',
                    'unitPrice': 8239.58},
 ('WDAL1', 214): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                  'deliverNum': 1705067,
                  'name': '配电箱',
                  'sequenceNum': 214,
                  'serialNum': 41,
                  'unit': '台',
                  'unitPrice': 4699.2},
 ('WDAL2', 215): {'amount': 1,
                  'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                  'deliverNum': 1705067,
                  'name': '配电箱',
                  'sequenceNum': 215,
                  'serialNum': 42,
                  'unit': '台',
                  'unitPrice': 3915.61},
 ('WDAPE1-1', 220): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                     'deliverNum': 1705067,
                     'name': '配电箱',
                     'sequenceNum': 220,
                     'serialNum': 43,
                     'unit': '台',
                     'unitPrice': 6576.19},
 ('WDAPE1-2', 221): {'amount': 1,
                     'deliverDate': datetime.datetime(2017, 5, 11, 0, 0),
                     'deliverNum': 1705067,
                     'name': '配电箱',
                     'sequenceNum': 221,
                     'serialNum': 44,
                     'unit': '台',
                     'unitPrice': 6576.19},
 ('WDATkt', '218变'): {'amount': 1,
                      'deliverDate': datetime.datetime(2017, 5, 9, 0, 0),
                      'deliverNum': 1705044,
                      'name': 'ATS箱',
                      'sequenceNum': '218变',
                      'serialNum': 1,
                      'unit': '台',
                      'unitPrice': 20259},
 ('WDATxt', 216): {'amount': 1,
                   'deliverDate': datetime.datetime(2017, 5, 9, 0, 0),
                   'deliverNum': 1705045,
                   'name': 'ATS箱',
                   'sequenceNum': 216,
                   'serialNum': 25,
                   'unit': '台',
                   'unitPrice': 13362.31},
 ('YAL1', 234): {'amount': 1,
                 'deliverDate': datetime.datetime(2017, 6, 2, 0, 0),
                 'deliverNum': '1706007',
                 'name': '配电箱',
                 'sequenceNum': 234,
                 'serialNum': 119,
                 'unit': '台',
                 'unitPrice': 15815.27},
 ('xfXJ', 62): {'amount': 1,
                'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                'deliverNum': 1706118,
                'name': '消防巡检柜',
                'sequenceNum': 62,
                'serialNum': 193,
                'unit': '台',
                'unitPrice': 73493.16},
 ('一层主机配电箱', 230): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                    'deliverNum': 1706038,
                    'name': '配电箱',
                    'sequenceNum': 230,
                    'serialNum': 168,
                    'unit': '台',
                    'unitPrice': 13114.58},
 ('主线1进1出:4*120+1*70', 1): {'amount': 1,
                            'deliverDate': datetime.datetime(2017, 5, 15, 0, 0),
                            'deliverNum': 1705100,
                            'name': 'T接箱',
                            'sequenceNum': 1,
                            'serialNum': 48,
                            'unit': '台',
                            'unitPrice': 1009.38},
 ('主线1进1出:4*120+1*70', 2): {'amount': 1,
                            'deliverDate': datetime.datetime(2017, 5, 15, 0, 0),
                            'deliverNum': 1705100,
                            'name': 'T接箱',
                            'sequenceNum': 2,
                            'serialNum': 49,
                            'unit': '台',
                            'unitPrice': 1009.38},
 ('主线1进1出:4*120+1*70', 7): {'amount': 1,
                            'deliverDate': datetime.datetime(2017, 5, 15, 0, 0),
                            'deliverNum': 1705100,
                            'name': 'T接箱',
                            'sequenceNum': 7,
                            'serialNum': 54,
                            'unit': '台',
                            'unitPrice': 1009.38},
 ('主线1进1出:4*120+1*70', 8): {'amount': 1,
                            'deliverDate': datetime.datetime(2017, 5, 15, 0, 0),
                            'deliverNum': 1705100,
                            'name': 'T接箱',
                            'sequenceNum': 8,
                            'serialNum': 55,
                            'unit': '台',
                            'unitPrice': 1009.38},
 ('主线1进1出:4*150+1*70', 9): {'amount': 1,
                            'deliverDate': datetime.datetime(2017, 5, 15, 0, 0),
                            'deliverNum': 1705100,
                            'name': 'T接箱',
                            'sequenceNum': 9,
                            'serialNum': 56,
                            'unit': '台',
                            'unitPrice': 1009.38},
 ('主线1进1出:4*185+1*95', 3): {'amount': 1,
                            'deliverDate': datetime.datetime(2017, 5, 15, 0, 0),
                            'deliverNum': 1705100,
                            'name': 'T接箱',
                            'sequenceNum': 3,
                            'serialNum': 50,
                            'unit': '台',
                            'unitPrice': 1009.38},
 ('主线1进1出:4*185+1*95', 4): {'amount': 1,
                            'deliverDate': datetime.datetime(2017, 5, 15, 0, 0),
                            'deliverNum': 1705100,
                            'name': 'T接箱',
                            'sequenceNum': 4,
                            'serialNum': 51,
                            'unit': '台',
                            'unitPrice': 1009.38},
 ('主线1进1出:4*185+1*95', 5): {'amount': 1,
                            'deliverDate': datetime.datetime(2017, 5, 15, 0, 0),
                            'deliverNum': 1705100,
                            'name': 'T接箱',
                            'sequenceNum': 5,
                            'serialNum': 52,
                            'unit': '台',
                            'unitPrice': 1009.38},
 ('主线1进1出:4*185+1*95', 6): {'amount': 1,
                            'deliverDate': datetime.datetime(2017, 5, 15, 0, 0),
                            'deliverNum': 1705100,
                            'name': 'T接箱',
                            'sequenceNum': 6,
                            'serialNum': 53,
                            'unit': '台',
                            'unitPrice': 1009.38},
 ('主线1进1出:4*25+1*16', 11): {'amount': 2,
                            'deliverDate': datetime.datetime(2017, 5, 15, 0, 0),
                            'deliverNum': 1705100,
                            'name': 'T接箱',
                            'sequenceNum': 11,
                            'serialNum': 58,
                            'unit': '台',
                            'unitPrice': 318.24},
 ('主线1进1出:4*25+1*16', 12): {'amount': 2,
                            'deliverDate': datetime.datetime(2017, 5, 15, 0, 0),
                            'deliverNum': 1705100,
                            'name': 'T接箱',
                            'sequenceNum': 12,
                            'serialNum': 59,
                            'unit': '台',
                            'unitPrice': 318.24},
 ('主线1进1出:4*95+1*50', 10): {'amount': 1,
                            'deliverDate': datetime.datetime(2017, 5, 15, 0, 0),
                            'deliverNum': 1705100,
                            'name': 'T接箱',
                            'sequenceNum': 10,
                            'serialNum': 57,
                            'unit': '台',
                            'unitPrice': 871},
 ('主线1进1出:5*16', 14): {'amount': 2,
                       'deliverDate': datetime.datetime(2017, 5, 15, 0, 0),
                       'deliverNum': 1705100,
                       'name': 'T接箱',
                       'sequenceNum': 14,
                       'serialNum': 60,
                       'unit': '台',
                       'unitPrice': 318.24},
 ('主线1进1出:5*16', 15): {'amount': 2,
                       'deliverDate': datetime.datetime(2017, 5, 15, 0, 0),
                       'deliverNum': 1705100,
                       'name': 'T接箱',
                       'sequenceNum': 15,
                       'serialNum': 61,
                       'unit': '台',
                       'unitPrice': 318.24},
 ('二层主机配电箱', 231): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                    'deliverNum': 1706038,
                    'name': '配电箱',
                    'sequenceNum': 231,
                    'serialNum': 169,
                    'unit': '台',
                    'unitPrice': 9423.28},
 ('四层主机配电箱', 232): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 6, 6, 0, 0),
                    'deliverNum': 1706038,
                    'name': '配电箱',
                    'sequenceNum': 232,
                    'serialNum': 170,
                    'unit': '台',
                    'unitPrice': 13408.36},
 ('机房照明', '增1-1'): {'amount': 1,
                    'deliverDate': datetime.datetime(2017, 6, 15, 0, 0),
                    'deliverNum': 1706117,
                    'name': '配电箱',
                    'sequenceNum': '增1-1',
                    'serialNum': 205,
                    'unit': '台',
                    'unitPrice': 915},
 (None, None): {'amount': '=SUM(F5:F221)',
                'deliverDate': None,
                'deliverNum': None,
                'name': '合计',
                'sequenceNum': None,
                'serialNum': None,
                'unit': None,
                'unitPrice': None}}